TIP-31 Bech32 Address Format (updated)
iotaledger/tips pull request #70
Opened 2022-04-04 13:08 UTC by lzpap

- Replaces [TIP-11](https://github.com/iotaledger/tips/blob/main/tips/TIP-0011/tip-0011.md)
 - Extends bech32 support for Alias and NFT addresses
 - Adds Shimmer HRPs `smr` and `rms`

2022-04-08 15:01 UTC, Wollac requested changes

2022-04-08 18:05 UTC, Thoralf-M commented on tips/TIP-0031/tip-0031.md
> +   - <i>NFT ID</i>, BLAKE2b-160 hash (20 bytes): `0x89168d92d0b88cdb4f80c0eb830bb4bed3441fcd`
With the Rust implementation I also get `0xa1d81f43cc3cc1fe80c594481a63de76eb0d23e1`

2022-04-13 08:45 UTC, lzpap commented on tips/TIP-0031/tip-0031.md
> +   - <i>NFT ID</i>, BLAKE2b-160 hash (20 bytes): `0x89168d92d0b88cdb4f80c0eb830bb4bed3441fcd`
Yep, `0xa1d81f43cc3cc1fe80c594481a63de76eb0d23e1` isthe correct value.

2022-04-13 09:02 UTC, lzpap commented on tips/TIP-0031/tip-0031.md
> + - Alias, where the address consists of the BLAKE2b-160 hash of the <i>Output ID</i> that created the alias.
Added a definition to TIP-20 https://github.com/lzpap/tips/commit/e2f59c7336569c8831716811ca05839d85a35cfb

2022-04-19 17:11 UTC, Wollac approved these changes

2022-04-19 17:13 UTC, Wollac commented on tips/TIP-0031/tip-0031.md
> + - Alias, where the address consists of the BLAKE2b-160 hash of the <i>Output ID</i> that created the alias.
:+1:

2022-07-05 13:15 UTC, alexsporn approved these changes

2022-07-05 14:04 UTC, Thoralf-M approved these changes

2022-07-05 14:08 UTC, merged